export type SentimentPoint = { time: string; value: number }; // -100 to 100
export type ScoreHistoryPoint = { date: string; score: number };

export interface EntityData {
    id: string;
    address: string; // The actual Ethereum address
    type: 'wallet' | 'contract' | 'nft' | 'token';
    score: number;
    label: 'Safe' | 'Caution' | 'High Risk';
    summary: string;
    aiText?: string;
    risks: { type: "success" | "warning" | "danger" | "info"; title: string; description: string }[];
    history: ScoreHistoryPoint[]; // For chart
    sentiment: SentimentPoint[]; // For sentiment widget
    hypeScore?: number; // 0-100 (New)
    mentionsCount?: number; // (New)
    nativeBalance?: number;
    nativeSymbol?: string;
    nativePriceUsd?: number;
    marketData?: { // (New)
        ethPriceUsd: number;
        portfolioValueUsd: number;
        tokenPrice?: number; // (New) Mock price for tokens
    };
}

export const MOCK_DB: Record<string, EntityData> = {
    // Scenario 1: High Trust Wallet
    "vitalik.eth": {
        id: "vitalik.eth (0xAb5...123)",
        address: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
        type: 'wallet',
        score: 98,
        label: 'Safe',
        summary: "High-reputation identity linked to verified ENS. Deep on-chain history with no malicious interactions detected.",
        risks: [
            { type: "success", title: "Verified Identity", description: "Linked to known public figure (ENS)." },
            { type: "success", title: "Clean History", description: "0 interactions with sanctioned mixers." },
            { type: "info", title: "Whale Activity", description: "High volume transactions detected regularly." }
        ],
        history: [
            { date: 'Jan', score: 95 }, { date: 'Feb', score: 96 }, { date: 'Mar', score: 98 }
        ],
        sentiment: [
            { time: '10:00', value: 80 }, { time: '12:00', value: 85 }, { time: '14:00', value: 90 }
        ]
    },

    // Scenario 2: Rug Pull Contract
    "0xBadContract": {
        id: "0x892...Bad1 (DeFi_Yield_V2)",
        address: "0x892345678901234567890123456789012345Bad1",
        type: 'contract',
        score: 12,
        label: 'High Risk',
        summary: "CRITICAL ALERT: Code similarity match with known rug-pull templates. Developer wallet funded by Tornado Cash.",
        risks: [
            { type: "danger", title: "Malicious Code", description: "Functions mimic 'SquidGame' token honeypot." },
            { type: "danger", title: "Wash Trading", description: "90% of volume is generated by 3 wallets." },
            { type: "warning", title: "Unverified Source", description: "Contract source code not verified on Etherscan." }
        ],
        history: [
            { date: 'Jan', score: 50 }, { date: 'Feb', score: 30 }, { date: 'Mar', score: 12 }
        ],
        sentiment: [
            { time: '10:00', value: -20 }, { time: '12:00', value: -60 }, { time: '14:00', value: -90 }
        ]
    },

    // Scenario 3: Fake NFT
    "bored_ape_6969": {
        id: "Bored Ape #6969 (Unverified Collection)",
        address: "0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D",
        type: 'nft',
        score: 45,
        label: 'Caution',
        summary: "Potential plagiarism detected. Artwork is 100% pixel match with BAYC #6969 but contract address differs.",
        risks: [
            { type: "danger", title: "Copycat Detected", description: "Image hash matches asset in another collection." },
            { type: "warning", title: "Low Liquidity", description: "Only 2 unique holders in history." },
            { type: "success", title: "Metadata Standards", description: "ERC-721 metadata structure is valid." }
        ],
        history: [
            { date: 'Jan', score: 45 }, { date: 'Feb', score: 45 }, { date: 'Mar', score: 45 }
        ],
        sentiment: [
            { time: '10:00', value: 0 }, { time: '12:00', value: -10 }, { time: '14:00', value: -15 }
        ]
    }
};

export function getAnalysis(query: string): EntityData {
    // Normalize
    const q = query.toLowerCase();

    if (q.includes("vitalik") || q.includes("safe")) return MOCK_DB["vitalik.eth"];
    if (q.includes("bad") || q.includes("risk") || q.includes("rug")) return MOCK_DB["0xBadContract"];
    if (q.includes("ape") || q.includes("nft")) return MOCK_DB["bored_ape_6969"];

    // Default Random
    const randomScore = Math.floor(Math.random() * 40) + 40;
    return {
        id: query,
        address: query.startsWith('0x') ? query : '0x0000000000000000000000000000000000000000',
        type: 'wallet',
        score: randomScore,
        label: randomScore > 70 ? 'Safe' : 'Caution',
        summary: "Analysis complete. Entity shows mixed signals across on-chain activity and social sentiment.",
        risks: [
            { type: "warning", title: "Insufficient Data", description: "Wallet has sparse transaction history." },
            { type: "info", title: "New Activity", description: "Active for less than 30 days." }
        ],
        history: [],
        sentiment: []
    };
}
